spring.application.name=OrderService

spring.datasource.url=jdbc:mariadb://localhost:3306/food_ordering_db
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8083
#Rate limit
# max 5 request
resilience4j.ratelimiter.instances.orderService.limitForPeriod=10
# time 1 minute
resilience4j.ratelimiter.instances.orderService.limitRefreshPeriod=1m
# wait 500ms before throw error
resilience4j.ratelimiter.instances.orderService.timeoutDuration=500ms


# circuit breaker
# ng??ng l?i 25%
resilience4j.circuitbreaker.instances.orderServiceCB.failure-rate-threshold=25
resilience4j.circuitbreaker.instances.orderServiceCB.sliding-window-size=5
resilience4j.circuitbreaker.instances.orderServiceCB.minimum-number-of-calls=4
# Th?i gian ch? ? tr?ng thái OPEN tr??c khi th? l?i (20 giây)
resilience4j.circuitbreaker.instances.orderServiceCB.wait-duration-in-open-state=20s

#Rety
# S? l?n th? l?i t?i ?a (bao g?m c? l?n g?i ??u tiên)
resilience4j.retry.instances.orderServiceRetry.max-attempts=3
# Kho?ng th?i gian ch? gi?a các l?n th? l?i
resilience4j.retry.instances.orderServiceRetry.wait-duration=2s
# Danh sách các l?i mu?n th? l?i
resilience4j.retry.instances.orderServiceRetry.retry-exceptions=org.springframework.web.client.ResourceAccessException

# Ép Retry ch?y ngoài cùng (?u tiên 1)
resilience4j.retry.retry-aspect-order=2
# Circuit Breaker ch?y sau (?u tiên 2)
resilience4j.circuitbreaker.circuitbreaker-aspect-order=1
# Rate Limiter ch?y trong cùng (?u tiên 3)
resilience4j.ratelimiter.ratelimiter-aspect-order=3